### ISSUE TITLE
No need for a sorted sentinel

### ISSUE THREAD

**Issue by Morwenn** [mattreecebentley/plf_indiesort#1]
The loop in indiesort that handles the permutation of the elements of the array after the indirect sort uses [a `sorted` condition][sorted-condition] to detect already sorted elements:

```cpp
if (current_tuple->original_index != index && current_tuple->original_index != sorted)
{
    // ...
}
```

The second part of the condition is unneeded if you manage to assign the right values so that all sorted elements satisfy the first condition `current_tuple->original_index == index`. Boost.Algorithm uses such a trick in the [`apply_permutation` algorithm][apply-permutation]. In plf_indiesort, it consists in changing this line:

```cpp
sort_array[destination_index].original_index = sorted;
```

Into this one:

```cpp
sort_array[destination_index].original_index = destination_index;
```

It can avoid a fair number of extra comparisons in some scenarios, and allows the algorithm to accept some exotic iterator types that have a `difference_type` not compatible with `std::numeric_limits`.

This permutation algorithm is really close from yours and is explained in details in [a series of articles][old-new-thing] by Raymond Chen.

  [apply-permutation]: https://github.com/boostorg/algorithm/blob/develop/include/boost/algorithm/apply_permutation.hpp#L56
  [old-new-thing]: https://devblogs.microsoft.com/oldnewthing/20170105-00/?p=95125
  [sorted-condition]: https://github.com/mattreecebentley/plf_indiesort/blob/master/plf_indiesort.h#L428

**Comment by mattreecebentley** [comment]
Thank you.
